name: bedrock_smith
description: "BedrockSmith: Add-on Load Order Manager and Mega-Pack Bundler"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.6
  archive: ^3.6.1
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#111418"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png